from django.core.exceptions import ValidationError
import re

def validate_move_name(value):
    pass
